/**
 * Moneyline-v0 — serve-time inference.
 *
 * Logistic regression with one anchor feature (raw log-odds) plus 11
 * standardized residuals. Mirrors what scripts/model/train-moneyline-v0.py
 * does at sklearn predict time:
 *
 *     scaled_i = (raw_i - scaler_mean_i) / scaler_scale_i   for each residual
 *     z = intercept
 *         + anchor_coef * raw_anchor
 *         + Σ residual_coef_i * scaled_i
 *     p_home = 1 / (1 + exp(-z))
 *
 * If isotonic_applied = true (not in v0; slot reserved per CEng condition),
 * a piecewise-linear isotonic table is applied to p_home before returning.
 *
 * Source of truth: models/moneyline/current/serving-params.json,
 * generated by scripts/model/export-moneyline-v0-node.py from the trained
 * joblib artifacts. Re-export after every retrain.
 */

import type { MoneylineV0Features } from '@/lib/features/moneyline-v0';
import servingParams from './serving-params.json';

interface IsotonicTable {
  x_thresholds: number[];
  y_thresholds: number[];
  out_of_bounds: 'clip';
}

interface ServingParams {
  model_id: string;
  trained_at_utc: string;
  holdout_declaration_id: string;
  intercept: number;
  anchor: { feature: string; coefficient: number };
  residual_features: string[];
  residual_coefficients_scaled: number[];
  scaler: { mean: number[]; scale: number[] };
  isotonic_applied: boolean;
  isotonic_table: IsotonicTable | null;
}

let validated: ServingParams | null = null;

function loadParams(): ServingParams {
  if (validated) return validated;
  const parsed = servingParams as ServingParams;
  if (parsed.residual_features.length !== parsed.residual_coefficients_scaled.length) {
    throw new Error('serving-params: feature/coefficient length mismatch');
  }
  if (parsed.scaler.mean.length !== parsed.residual_features.length) {
    throw new Error('serving-params: scaler.mean dimension mismatch');
  }
  validated = parsed;
  return validated;
}

function applyIsotonic(p: number, table: IsotonicTable): number {
  const xs = table.x_thresholds;
  const ys = table.y_thresholds;
  if (xs.length === 0) return p;
  if (p <= xs[0]) return ys[0];
  if (p >= xs[xs.length - 1]) return ys[ys.length - 1];
  let lo = 0;
  let hi = xs.length - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (xs[mid] <= p) lo = mid;
    else hi = mid;
  }
  const span = xs[hi] - xs[lo];
  if (span === 0) return ys[lo];
  const t = (p - xs[lo]) / span;
  return ys[lo] + t * (ys[hi] - ys[lo]);
}

function sigmoid(z: number): number {
  if (z >= 0) {
    const e = Math.exp(-z);
    return 1 / (1 + e);
  }
  const e = Math.exp(z);
  return e / (1 + e);
}

/**
 * P(home wins) given the raw 12-feature payload built by
 * `apps/web/lib/features/moneyline-v0.ts`. Throws on missing fields.
 * Returns a number in (0, 1).
 */
export function predictHomeWinProb(features: MoneylineV0Features): number {
  const p = loadParams();
  let z = p.intercept + p.anchor.coefficient * features.market_log_odds_home;
  for (let i = 0; i < p.residual_features.length; i++) {
    const name = p.residual_features[i] as keyof MoneylineV0Features;
    const raw = features[name];
    if (typeof raw !== 'number' || !Number.isFinite(raw)) {
      throw new Error(`predictHomeWinProb: feature ${name} is not finite (got ${raw})`);
    }
    const scaled = (raw - p.scaler.mean[i]) / p.scaler.scale[i];
    z += p.residual_coefficients_scaled[i] * scaled;
  }
  let prob = sigmoid(z);
  if (p.isotonic_applied && p.isotonic_table) {
    prob = applyIsotonic(prob, p.isotonic_table);
  }
  // Clamp to (1e-6, 1 - 1e-6) so downstream EV / log-odds math doesn't blow up.
  if (prob < 1e-6) prob = 1e-6;
  if (prob > 1 - 1e-6) prob = 1 - 1e-6;
  return prob;
}

/**
 * EV-to-tier mapping for v0. EV is the model's expected value in units
 * (e.g. +0.025 = +2.5% expected return on a 1-unit bet at the offered price).
 * Returns null when EV is below the +2% publish floor.
 *
 * Tier ladder (v0 cold-start; tightened later if calibration permits):
 *   EV ≥ 0.06 → tier 5 → required_tier = 'elite'
 *   EV ≥ 0.04 → tier 4 → required_tier = 'pro'
 *   EV ≥ 0.02 → tier 3 → required_tier = 'pro'
 *   EV < 0.02 → not published (returns null)
 */
export function tierFromEv(ev: number):
  | { confidence_tier: number; required_tier: 'pro' | 'elite' }
  | null {
  if (ev >= 0.06) return { confidence_tier: 5, required_tier: 'elite' };
  if (ev >= 0.04) return { confidence_tier: 4, required_tier: 'pro' };
  if (ev >= 0.02) return { confidence_tier: 3, required_tier: 'pro' };
  return null;
}

/** EV from a model probability vs an American odds price. */
export function evFromAmericanPrice(modelProb: number, americanPrice: number): number {
  const decimalPayoff =
    americanPrice >= 100 ? americanPrice / 100 : 100 / Math.abs(americanPrice);
  return modelProb * decimalPayoff - (1 - modelProb);
}
