/**
 * Playwright configuration for Diamond Edge E2E tests.
 *
 * Scope: golden-path E2E across auth, subscription, slate, pick detail, bankroll.
 * Level: E2E
 * Data setup: test DB seeded via tests/fixtures/seed.ts; auth state stored per test user.
 * Flake risk: Supabase local startup latency (mitigated by webServer.reuseExistingServer).
 * CI gating: BLOCKING — all E2E tests must pass before staging deploy is permitted.
 *
 * Run locally: npx playwright test
 * Run in CI:   npx playwright test --reporter=github
 */

import { defineConfig, devices } from '@playwright/test';
import path from 'path';

// Test auth state files — one per user tier. Generated by tests/e2e/helpers/auth.setup.ts.
export const AUTH_STATE = {
  free: path.join(__dirname, '.auth', 'free-user.json'),
  pro: path.join(__dirname, '.auth', 'pro-user.json'),
  elite: path.join(__dirname, '.auth', 'elite-user.json'),
} as const;

export default defineConfig({
  testDir: __dirname,
  // Glob pattern — test files only (not helpers/fixtures)
  testMatch: '**/*.spec.ts',

  // Maximum time per test. Increased for E2E against a local Next.js dev server.
  timeout: 30_000,

  // Expect timeout — how long locator.waitFor() / expect() retries before failing.
  expect: { timeout: 8_000 },

  // Do not retry in local dev (catch flakes early). CI retries once to filter true flakes.
  retries: process.env.CI ? 1 : 0,

  // Serial workers in CI to avoid port conflicts; parallel locally.
  workers: process.env.CI ? 1 : undefined,

  reporter: process.env.CI
    ? [['github'], ['html', { open: 'never' }]]
    : [['list'], ['html', { open: 'on-failure' }]],

  use: {
    // Base URL — Next.js dev server on 3000 by default.
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:3000',

    // Collect traces on first retry to diagnose CI failures.
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    // -----------------------------------------------------------------------
    // Auth setup — runs first to generate stored auth state for each tier.
    // These are prerequisites for the golden-path projects below.
    // -----------------------------------------------------------------------
    {
      name: 'setup-auth',
      testMatch: '**/helpers/auth.setup.ts',
      use: { ...devices['Desktop Chrome'] },
    },

    // -----------------------------------------------------------------------
    // Golden-path suites — each depends on auth setup completing first.
    // -----------------------------------------------------------------------
    {
      name: 'auth-flows',
      testMatch: '**/auth.spec.ts',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup-auth'],
    },
    {
      name: 'slate',
      testMatch: '**/slate.spec.ts',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup-auth'],
    },
    {
      name: 'pick-detail',
      testMatch: '**/pick-detail.spec.ts',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup-auth'],
    },
    {
      name: 'subscription',
      testMatch: '**/subscription.spec.ts',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup-auth'],
    },
    {
      name: 'bankroll',
      testMatch: '**/bankroll.spec.ts',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup-auth'],
    },
  ],

  // Start the Next.js dev server before any tests run.
  // reuseExistingServer = true so local `npm run dev` sessions aren't killed.
  webServer: {
    command: 'npm run dev',
    cwd: path.resolve(__dirname, '../../apps/web'),
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
    env: {
      // Point at the local Supabase test instance (supabase start)
      NEXT_PUBLIC_SUPABASE_URL: process.env.TEST_SUPABASE_URL ?? 'http://localhost:54321',
      NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.TEST_SUPABASE_ANON_KEY ?? 'test-anon-key',
      SUPABASE_SERVICE_ROLE_KEY: process.env.TEST_SUPABASE_SERVICE_KEY ?? 'test-service-key',
      // Stub external APIs — never hit live endpoints in E2E
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_test_stub',
      STRIPE_SECRET_KEY: 'sk_test_stub',
      ANTHROPIC_API_KEY: 'sk-ant-stub',
      ODDS_API_KEY: 'stub',
      UPSTASH_REDIS_REST_URL: 'http://localhost:6379',
      UPSTASH_REDIS_REST_TOKEN: 'stub',
      CRON_SECRET: 'test-cron-secret',
      NEXT_PUBLIC_APP_URL: 'http://localhost:3000',
    },
  },
});
